### PR TITLE
Add awbg setting

### PR DESCRIPTION
**Pull request by langolierz**
when i run an example trying to set the gains the following error is logged:

```
[ error ] OMX_ERRORTYPE ofxRPiCameraVideoGrabber::setWhiteBalanceGains(int, int): 1244 OMX_ErrorVersionMismatch
```

i can not figure out what versions are being used or what is mismatched.

this commit seems to add the awbg option... https://github.com/raspberrypi/userland/commit/1b6e913f53b7348ee89b73a996a090c869dbd4fc

### CODE REVIEW

**Comment by jvcleave** [comment]
it looks like you aren't initing `whiteBalanceGainsConfig`

try adding to `resetValues`

```
  OMX_INIT_STRUCTURE(whiteBalanceGainsConfig);
    whiteBalanceGainsConfig.nPortIndex = OMX_ALL;
```

**Comment by langolierz** [comment]
@jvcleave yess! that worked , didnt need to set the [nPortIndex](https://github.com/raspberrypi/userland/blob/master/interface/vmcs_host/khronos/IL/OMX_Broadcom.h#L2387) as it doesnt have one , but just the initing line was all it needed (doh that i missed that !) is this something you would like merged back into your repo ? also i needed to set gains to 65536 to get 100% , im guessing maybe this should be converted although i cant see another example in your code of how you would do this ?

**Comment by jvcleave** [comment]
this may help

https://github.com/jvcleave/ofxRPiCameraVideoGrabber/blob/704a1386fc1ffb6b4804537a446bbd672c4da151/src/OMX_Maps.h#L1187

**Comment by langolierz** [comment]
@jvcleave thank you that worked perfectly ! still gonna try mucking around with changing the sensor mode some more , but will open a pr into your repo after if you want

**Pull request merged**
